### ISSUE TITLE
Extra "," after last username

### ISSUE THREAD

**Issue by Eldenroot** [SvePu/Profile-Visitors#4]
Extra "," after last username in profile

**Comment by SvePu** [comment]
Hi, what do you mean?

**Comment by SvePu** [comment]
Fixed it here: https://github.com/SvePu/Profile-Visitors/issues/1

**Comment by Eldenroot** [comment]
@SvePu - sorry for late reply... I still see them with latest version from mybb mod site
![extra_comma](https://cloud.githubusercontent.com/assets/778890/12092744/3bf9680a-b2ff-11e5-931d-926236e1893b.png)

**Comment by SvePu** [comment]
@Cu8eR - Ahhh OK...your're right ... on mybb mod site is still version 1.3 online ... I'll update it asap..

**Comment by Eldenroot** [comment]
@SvePu - OK, thank you... It would be perfect if you can also fix this #3 because I cannot translate it into my language (special characters are replaced by ??????)
